### PR TITLE
[WIP] The Second Patch PR

### LINKED ISSUE #17: The Second Patch
Here we go, round 2.

- [x] Fix `try` function (type inference issues)
- [x] Implement table-based ~~vararg~~ support for `try` & `coroutine:resume`/`yield`
- [x] Write docs for the new functions (mostly selfaware2)
- [x] Set E2 function costs (make some benchmark kind of testing and find a good balance)
- [ ] Fix any remaining bugs?

### PR DESCRIPTION
**Pull request by Cheatoid**
Here we go.
Fixes #17.

Work in progress.

### CODE REVIEW

**Comment by Cheatoid** [comment]
```golo
function table myFunc( Data:table )
{
    print( "[ myFunc data table ]" )
    printTable( Data )
    return table( "Coming back...", owner() )
}

local Args = table( "Input arguments here...", 1234 )
local TryResult = try( "myFunc", Args )
print( "[ try call ]" )
printTable( TryResult )
print( "[ try call typeids ]" )
printTable( TryResult:typeids() )
```

⬇️ Works great 🎉
```
[ myFunc data table ]
1	=	Input arguments here...
2	=	1234
[ try call ]
1	=	1
2:
		1	=	Coming back...
		2	=	Player [1][0]
[ try call typeids ]
1	=	n
2	=	t
```

**Comment by Cheatoid** [comment]
```golo
@persist C:coroutine

function table fun(Args:table)
{
    print("Hello from coroutine. Args:")
    printTable(Args)
    local Stuff = coroutineYield(table("What's up main thread?"))
    print("We are back in, coroutine received stuff from main:")
    printTable(Stuff)
    return table("Coroutine says bye")
}

C = coroutine("fun", table("Initial arguments for coroutine"))
local Returned = C:resume(table("More data for coroutine"))
print("Main received stuff from coroutine:")
printTable(Returned)
print("Coroutine status: " + C:status())
Returned = C:resume(table("Final stuff for coroutine"))
print("Main received stuff from coroutine:")
printTable(Returned)
print("Coroutine status: " + C:status())
```

More awesome stuff. Seems to work good enough. (E2 will error if you use non-table overloads, which is nice.)

```
Hello from coroutine. Args:
1	=	Initial arguments for coroutine
Main received stuff from coroutine:
1	=	What's up main thread?
Coroutine status: suspended
We are back in, coroutine received stuff from main:
1	=	Final stuff for coroutine
Main received stuff from coroutine:
1	=	Coroutine says bye
Coroutine status: dead
```

**Comment by Cheatoid** [comment]
@Vurv78 Pull and give it a try 😃

**Comment by Vurv78** [comment]
Still need to add the opcosts for everything + the docs, Also I wanted to add some extra functionality. I already said I was working on it, did get pretty far and found some stuff to fix

Tables are fine for now, but at some point I'll try and change the function to allow varargs properly. Will take a while though.
Also, there's a bug for printGlobal I need to fix

**Comment by Cheatoid** [comment]
Leaving the note about `validArray` (helper) function:
This is actually wrong; E2 arrays can have "holes" (or gaps) in them...
Therefore they are not always sequential, fun xD
For example: `array((123) = "lol")` creates an array with a string value at index 123.
This should be checking that there are no string indexes, in other words all keys must be numeric, and if so, then treat it as array.

**Comment by Cheatoid** [comment]
Oh that's it, I know I got an idea! A simple trick that will make `try` work much better! Possibly, perfectly!!

**Comment by Cheatoid** [comment]
Damn right, genius idea. IT WORKS PERFECTLY!!!
Why didn't we think of this before...
**Test E2 code**:
```golo
function array lets_GOOOOO()
{
    return array((100) = "Goooooo!", (200) = vec(1, 2, 3), (9001) = matrix(entity():angles()))
}

local TryResult = try( "lets_GOOOOO" )

print( "[try result]" )
printTable( TryResult )

print( "[try result typeids]" )
printTable( TryResult:typeids() )

print( "[try return value]" )
local ReturnedArray = TryResult[ 2, array ]
print( "ReturnedArray[100, string]", ReturnedArray[ 100, string ] )
print( "ReturnedArray[200, vector]", ReturnedArray[ 200, vector ] )
print( "ReturnedArray[9001, matrix]", ReturnedArray[ 9001, matrix ] )
```
**Outputs**:
```
[try result]
2:
		9001	=	[0.99999994039536,-0,1.7484555314695e-07,0,1,0,-1.7484555314695e-07,0,0.99999994039536]
		100	=	Goooooo!
		200	=	[1,2,3]
1	=	1
[try result typeids]
1	=	n
2	=	r
[try return value]
ReturnedArray[100, string]	Goooooo!
ReturnedArray[200, vector]	[1,2,3]
ReturnedArray[9001, matrix]	[0.99999994039536,-0,1.7484555314695e-07,0,1,0,-1.7484555314695e-07,0,0.99999994039536]
```

**Comment by Cheatoid** [comment]
A test with the new `try` overload:
```golo
function table fun(Data:table)
{
    print("[ fun Data ]")
    printTable(Data)
    print("[ fun Data typeids ]")
    printTable(Data:typeids())
    return table((100) = "Goooooo!", (200) = vec(1, 2, 3), (9001) = matrix(entity():angles()))
}

local TryResult = try("fun", table(("Me") = owner(), ("Rot") = owner():eyeAngles()))

print("[ try result ]")
printTable(TryResult)

print("[ try result typeids ]")
printTable(TryResult:typeids())

print("[ try return value ]")
local ReturnedValue = TryResult[2, table]
printTable(ReturnedValue)

print("[ try return value typeids ]")
printTable(ReturnedValue:typeids())
```
**Outputs**:
```
[ fun Data ]
Rot	=	[14.981979370117,-90.023979187012,0]
Me	=	Player [1][0]
[ fun Data typeids ]
Me	=	e
Rot	=	a
[ try result ]
2:
		9001	=	[7.6427418606588e-15,-0.99999994039536,-8.7422769468049e-08,-8.7422769468049e-08,-8.7422776573476e-08,0.99999988079071,-0.99999994039536,-0,-8.7422776573476e-08]
		200	=	[1,2,3]
		100	=	Goooooo!
1	=	1
[ try result typeids ]
1	=	n
2	=	t
[ try return value ]
9001	=	[7.6427418606588e-15,-0.99999994039536,-8.7422769468049e-08,-8.7422769468049e-08,-8.7422776573476e-08,0.99999988079071,-0.99999994039536,-0,-8.7422776573476e-08]
200	=	[1,2,3]
100	=	Goooooo!
[ try return value typeids ]
9001	=	m
200	=	v
100	=	s
```

**Comment by Cheatoid** [comment]
Now the only stuff left to do: docs. 😄

**Comment by Cheatoid** [comment]
There's some cleanup work to do, I am on it.

**Comment by Vurv78** [comment]
Not going to mess with any of your code, just expanded validArray so we can use it in printGlobal rather than making a function there

**Comment by Cheatoid** [comment]
@Vurv78 i might have messed it up... it didn't let me pull your changes. for whatever reason i clicked to force it :/

**Comment by Cheatoid** [comment]
I'll work on docs now.

**Comment by Cheatoid** [comment]
@Vurv78 Review time?

**Comment by Cheatoid** [comment]
Should be more stable at this point.

**Comment by Cheatoid** [comment]
Uh what just happened?

**Comment by Vurv78** [comment]
You *did* mean this was ready if it was reviewed, right? Kinda merged before thinking..

Looks fine to me and you did tests along the way
I also test everything again when we are making a new release anyway

**Comment by Vurv78** [comment]
wtf is that revert

**Comment by Cheatoid** [comment]
Yeah it was ready for final review and then merge... idk what you did tho xD

**Comment by Cheatoid** [comment]
I am not going to press "Delete branch" just in case, can you revert the revert?

**Comment by Cheatoid** [comment]
By the way, I was planning to make one more patch, the 3rd one. So it is fine to split up some work.

Looks like it is all fine, according to this page:
https://github.com/Vurv78/VExtensions/commits/master

**Comment by Vurv78** [comment]
There you go, I think it only reverted it for the branch since main's last commit is still this PR

**Pull request merged**
